trigger:
- master
- refs/tags/{tagname}

resources:
- repo: self

variables:
  name: 'devopsdemo-template-go'
  tag:  '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - bash: |
          cd api_tests
          docker-compose run tests
          docker-compose run --entrypoint /bin/cat app /app/test-results.xml > ../test-results.xml
        displayName: Run Tests
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-results.xml'
          testRunTitle: Unit tests
          failTaskOnFailedTests: true
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'api_tests/results/api-test-results.xml'
          testRunTitle: API tests
          failTaskOnFailedTests: true
      - task: Docker@2
        displayName: Login to Docker registry
        inputs:
          command: login
          containerRegistry: registry # a service connection that you must set up first
      - task: Docker@2
        displayName: Build and Push
        inputs:
          command: buildAndPush
          repository: $(name)
          tags: |
            $(tag)
