version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    environment:
      - DEBUG_LEVEL: DEBUG
    restart: false

  # run with: docker-compose run tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: false

  # add any other containers such as DB, Redis, Mocks, ...